
target 'Mac-Kline' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods Mac-KLine
  #pod 'Alamofire'
  #pod 'Moya'
  pod 'SwiftyJSON'
  # UI
  pod 'SnapKit'

end
